### ISSUE TITLE
install procedure is not completable because of undefined variable

### ISSUE THREAD

**Issue by jamesloper** [rnmapbox/maps#1788]
**Describe the bug**  
When running `pod install` I get `undefined method 'pre_install' for nil:NilClass`. I am looking at the documentation at
https://github.com/rnmapbox/maps/blob/HEAD/ios/install.md and it references `$RNMapboxMaps` but that variable is not defined. Looking at the source code, the correct variable seems to be `$RNMBGL`. It seems like one of these variables should be reconciled into one variable.

**To Reproduce**  
```
yarn add @react-native-mapbox-gl/maps
npx pod-install
```

**Expected behavior**  
`pod install` completes

**Actual behavior**  
```
[!] An error occurred while processing the pre-install hook of the Podfile.

undefined method 'pre_install' for nil:NilClass
```

**Comment by luisdesouza10** [comment]
Same error here

**Comment by mfazekas** [comment]
This is a breaking change with the unreleased 10* version currently on main. I've added a not to clarify this.

https://github.com/rnmapbox/maps/blob/main/README.md#-this-readme-is-for-the-unreleased-10-branch-please-see-v8-branch-for-documentation-on-8-releases-

**Comment by finik-htec** [comment]
Not sure if this can help you, but in order to get v10 working, i had to add
` 
pod 'rnmapbox-maps', :path => '../node_modules/@react-native-mapbox-gl/maps'
`
in Podifle, and also default_ios_mapbox_v10_version was unknown variable, so i replaced it with rnMapboxMapsDefaultMapboxVersion just to make working prototope  (it would probably need to be patched). 
@mfazekas Please correct me if i made some mistake

**Comment by finik-htec** [comment]
@mfazekas Oh yeah, exactly!
