### ISSUE TITLE
Autolinking broken + possible fix

### ISSUE THREAD

**Issue by jbreuer95** [rnmapbox/maps#1824]
[#0e12d601df7e4f59f6feaaf50a7a656a4c36fd92](https://github.com/rnmapbox/maps/commit/0e12d601df7e4f59f6feaaf50a7a656a4c36fd92) deleted maps/ios/RCTMGL.xcodeproj/project.pbxproj

Without this file autolinking does not work for some reason. 
 
To test you can use `npx react-native link @rnmapbox/maps` without the project.pbxproj no file gets added to the Podfile.
With project.pbxproj the line is added again. I do not own a Macbook so i cannot generate a pbxproj for a PR i'm afraid. 

It seems a pbxprojPath is needed for react-native to recognise the iOS platform when linking.

**Comment by mfazekas** [comment]
@jbreuer95 for which RN version is it an issue?!

npx react-native link @rnmapbox/maps should not be necessary, on any recent version of `react-native`
This command (aka link) adds something like:

```
pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'
```


But since 0.60 this is not necessary - https://reactnative.dev/blog/2019/07/03/version-60#native-modules-are-now-autolinked

For 0.60 and later versions the `use_native_modules!` line should detect and load pod files from node_modules.
https://github.com/react-native-community/cli/blob/master/packages/platform-ios/native_modules.rb#L90


Might be related (https://github.com/react-native-community/cli/issues/1054)

**Comment by mfazekas** [comment]
@jbreuer95 sorry I was wrong. it seems that all of it goes to `npx @react-native-community/cli config`. and it does not report "@rnmapbox/maps" unless there the the pbxproj, as a workaround I've added https://github.com/rnmapbox/maps/commit/b37b09e64f0bf9e7dd73f0f157d88f00a7727cbf it does fix the issue according to my testing

**Comment by jbreuer95** [comment]
@mfazekas It works :D, I can see the lib again in the autolinking list! 
Nice fix, I was gonna suggest adding an empty project.pbxproj file but this is much cleaner.

**Comment by jbreuer95** [comment]
EAS build also succeeded!
