### ISSUE TITLE
A few typescript components being included / Atmosphere.tsx type issue

### ISSUE THREAD

**Issue by natew** [rnmapbox/maps#2140]
Sorry to skip env info since this is just a published package files thing:

<img width="855" alt="image" src="https://user-images.githubusercontent.com/12100/185764303-32510c6e-5dc4-400f-84df-fb70bdecad1d.png">

Seems like just a few of the `components/*` are staying as TS. I can't for the life of me get typescript to ignore this for some reason, despite many different `exclude` attempts.

**Comment by mfazekas** [comment]
@natew 
>  just a published package files thing:
not sure what you mean by that.

> components/* are staying as TS.
we're migrating to typescript and only some of the components are written in typescript, so that's why you see tsx and js mixed.

We'll need instructions to reproduce otherwise it's hard for us to fix issues. What is you rn version, and can you try with a more recent react-native version?!

**Comment by SkySails** [comment]
I think this issue should be reopened, as I believe that it highlights a real issue that doesn't depend on the react-native version.

First of all - I'm super happy to see that this library is migrating to Typescript! I myself use Typescript in my projects so this new direction is more than welcome. I also want to thank you and everyone working on this library for your work going into this, I really appreciate what you guys are doing!

With this said, however, this library currently _publishes_ Typescript code _mixed_ with JavaScript, which isn't ideal. This forces anyone who wants to use the library to set up their project to handle the compilation of typescript files since the final bundle needs to be JS.

In contrast, the usual scenario would be to write the project source code in TS, and then compile it to JavaScript + _declaration files_ before the package is published. This makes sure that the library is usable even without a typescript compiler, and thanks to the declaration files the types are still there for TS users to enjoy!

Judging by the screenshot in the initial post, @natew seems to stumble upon type issues when his TS-compiler tries to compile a `.tsx` file. It looks to me like it is importing something from a normal JS file, leading to type incompatibility as the JS file has no typing.

@natew If you found a way to make the compiler ignore these files, I'd be happy to hear about it since I have the same issue!

**Comment by SkySails** [comment]
@natew Alright, I made a workaround that'll work for now. Basically, I patched the library to import files from `./lib/javascript` instead of `./javascript` and then ran the TS compiler from the root of the library. In its current state with only a few TS files and the rest in JS, I had to set `noImplicitAny` and `declaration` to false in order to successfully compile it. This, unfortunately, means that the benefits of using TS in some files are no longer applicable, but if you _would_ generate declarations the main `MapboxGL` namespace would be typed as `any`. For now, the normal "implicit" types (and the ones in `index.d.ts`) are better.

Here's the patch:

```patch
diff --git a/node_modules/@rnmapbox/maps/index.d.ts b/node_modules/@rnmapbox/maps/index.d.ts
index 9aacd3e..b1b08d3 100644
--- a/node_modules/@rnmapbox/maps/index.d.ts
+++ b/node_modules/@rnmapbox/maps/index.d.ts
@@ -32,14 +32,14 @@ import {
   CameraBoundsWithPadding as _CameraBoundsWithPadding,
   CameraStops as _CameraStops,
   CameraAnimationMode as _CameraAnimationMode,
-} from './javascript/components/Camera';
-import { Atmosphere as _Atmosphere } from './javascript/components/Atmosphere';
+} from './lib/javascript/components/Camera';
+import { Atmosphere as _Atmosphere } from './lib/javascript/components/Atmosphere';
 import type {
   MapboxGLEvent as _MapboxGLEvent,
   UserTrackingMode as _UserTrackingMode,
   UserTrackingModeChangeCallback as _UserTrackingModeChangeCallback,
-} from './javascript/types/index';
-import type { requestAndroidLocationPermissions as _requestAndroidLocationPermissions } from './javascript/requestAndroidLocationPermissions';
+} from './lib/javascript/types/index';
+import type { requestAndroidLocationPermissions as _requestAndroidLocationPermissions } from './lib/javascript/requestAndroidLocationPermissions';
 
 // prettier-ignore
 type ExpressionName =
diff --git a/node_modules/@rnmapbox/maps/package.json b/node_modules/@rnmapbox/maps/package.json
index 9fef883..c8a6c60 100644
--- a/node_modules/@rnmapbox/maps/package.json
+++ b/node_modules/@rnmapbox/maps/package.json
@@ -6,9 +6,9 @@
     "access": "public"
   },
   "author": "React Native Mapbox Team",
-  "main": "./javascript/index.js",
-  "browser": "./javascript/index.web.js",
-  "react-native": "./javascript/index.js",
+  "main": "./lib/javascript/index.js",
+  "browser": "./lib/javascript/index.web.js",
+  "react-native": "./lib/javascript/index.js",
   "keywords": [
     "gl",
     "ios",
```

And here's the package-scripts used to apply the patch and compile the library:
```json
{
  "scripts": {
    "postinstall": "patch-package && yarn set-config local && yarn compile-mbgl",
    "compile-mbgl": "cd node_modules/@rnmapbox/maps && tsc --declaration false --noImplicitAny false"
  }
}
```

**Comment by natew** [comment]
Yea this one should be re-opened. I'm going to do something similar and run esbuild over the library and save a patchfile.

**Comment by mfazekas** [comment]
@natew I'm happy to reopen as soon as instructions are provided to reproduce the issue. Thanks for your understanding. Ideally instructions starts with something like:`react-native init ... --version 0.68.2` etc.

**Comment by natew** [comment]
Happy to do that when I find time. The issue exists for basically all installs though so likely worth keeping open for others to see.

**Comment by mattijsf** [comment]
I'm also facing this issue after trying out v10. I will see if I can write up some instructions to reproduce...
