### ISSUE TITLE
Code generation can reference multiple SDK versions for different generated files

### ISSUE THREAD

**Issue by naftalibeder** [rnmapbox/maps#2162]
The generated file `ios/RCTMGL-v10/RCTMGLStyle` is missing the following properties:

```
FillExtrusionLayer
- fillExtrusionEdgeRadius
- fillExtrusionAmbientOcclusionIntensity
- fillExtrusionAmbientOcclusionIntensityTransition
- fillExtrusionAmbientOcclusionRadius
- fillExtrusionAmbientOcclusionRadiusTransition

Atmosphere
- colorTransition
- highColorTransition
- spaceColorTransition
- horizonBlendTransition
- starIntensityTransition
```

I followed the autogenerate code around for a while, but I'm ultimately not sure what to update. @mfazekas any pointers?

**Comment by mfazekas** [comment]
> The generated file `ios/RCTMGL-v10/RCTMGLStyle` is missing the following properties:
> 
> ```
> FillExtrusionLayer
> - fillExtrusionEdgeRadius
> - fillExtrusionAmbientOcclusionIntensity
> - fillExtrusionAmbientOcclusionIntensityTransition
> - fillExtrusionAmbientOcclusionRadius
> - fillExtrusionAmbientOcclusionRadiusTransition
> 
> Atmosphere
> - colorTransition
> - highColorTransition
> - spaceColorTransition
> - horizonBlendTransition
> - starIntensityTransition
> ```
> 
> I followed the autogenerate code around for a while, but I'm ultimately not sure what to update. @mfazekas any pointers?


```sh
yarn fetch:style:spec
yarn generate
```

But we rely on https://raw.githubusercontent.com/mapbox/mapbox-gl-js/master/src/style-spec/reference/v8.json to contain those and I don't see fillExtrusionEdgeRadius in the one we have in the repo, but I see in the current so fetch:style:spec might solve it

**Comment by naftalibeder** [comment]
After a bunch of reinstalling and Ruby version madness, all of the other properties are there except `fillExtrusionEdgeRadius`, which is still missing from `FillExtrusionLayer.swift`. Can you verify that doesn't happen for you?

**Comment by naftalibeder** [comment]
Oh no way - so it wasn't that `FillExtrusionLayer.swift` was erroneously missing `fillExtrusionEdgeRadius` - the issue was that I had a cached (?!) version of `RCTMGLStyle.swift` that was mistakenly calling `layer.setFillExtrusionEdgeRadius`! Well, it's working now.

**Comment by naftalibeder** [comment]
@mfazekas Ok the issue seemed to be that I had

```
// myProject/ios/Podfile
$RNMapboxMapsVersion = '~> 10.6.1'
```

in my local project's `Podfile`, while the file `rnmapbox-maps.podspec`, which `autogenerate.js` reads, had the default iOS version set to

```
// myProject/node_modules/@rnmapbox/maps/rnmapbox-maps.podspec
rnMapboxMapsDefaultMapboxVersion = '~> 10.7.0'
```

It seems like all of the generated class definitions were getting installed based on `10.6.1` during `pod install`, so they did not have transitions properties. But `autogenerate.js` was reading version `10.7.0` and therefore creating `set*Transitiion` functions in `RCTMGLStyle.swift`, which referenced non-existent properties.

Changing my project's `$RNMapboxMapsVersion` to match `10.7.0` fixed it.

This is a bug, no? Seems to me that the generate script should take the enclosing project's SDK version into account - so perhaps documentation generation should run on commits, but code generation should probably happen during installation.

(For the record, I was referencing a local installation, e..g `npm i ../rnmapbox`, but I don't think that should matter?)

**Comment by mfazekas** [comment]
> This is a bug, no? Seems to me that the generate script should take the enclosing project's SDK version into account - so perhaps documentation generation should run on commits, but code generation should probably happen during installation.

So currently we generate code for the default version of mapbox dep (1.7.0 currently). This has the downside that if someone want's to use an earlier version with style changes they have to use something like `patch-package` to achieve that.

I assume we could generate code at pod install time on iOS, and probably we can solve that with gradle too. 

But I think that can have issue too. Like they set to RNMapboxMapsVersion=2.0 but we don't support some of the new naming conventions/types introduced in that lib, then the generated code will not compile.

I think in docs we should discourage people from setting `RNMapboxMapsVersion` unless they really need that. Also we can issue warning if RNMapboxMapsVersion set to lower than default.

But I assume for most cases this issue can happen if someone sets `RNMapboxMapsVersion` to consume a new version of the lib, then they upgrade the js lib and suddenly new version becomes old version.. Like default is 1.5.0, but they set RNMapboxMapsVersion to 1.6.0 to use the latest & greatest native libs. But then they upgrade the @rnmapbox/maps pkg and that now default to 1.7.0 with code generated for that. And I assume $RNMapboxMapsVersion=1.6.0 downgrade from 1.7.0 is no longer intentional, just they forgot to change it with the pkg upgrade.

**Comment by mfazekas** [comment]
For now I've documented that we don't recommend people adjusting version unless they know what they are doing. 

We could issue a warning if user set the version to lower than what we were building for, but it's a low priority task ATM.
