### ISSUE TITLE
Grouping different layers of ShapeSource using SymbolLayer

### ISSUE THREAD

**Issue by vladyslavnn** [rnmapbox/maps#2282]
I have a problem with ShapeSource clusterization using SymbolLayer. I have several layers and I want them to look like independent icons. But when it comes to layer overlapping some part of my icons(layer) overlaps others as shown in the screenshot.

<img width="201" alt="image" src="https://user-images.githubusercontent.com/102153444/194556186-82a4ed86-00b0-48c0-9ddf-70b5f7313b9b.png">

<img width="193" alt="image" src="https://user-images.githubusercontent.com/102153444/194556219-8fb0cd5d-20b3-4af6-a614-08cc42254668.png">

The best solution I've found now is to add marker images with stars as one image but solution is pretty hucky and it will be much harder to maintain.

<img width="222" alt="image" src="https://user-images.githubusercontent.com/102153444/194556374-d013fb97-80bf-436f-831f-f88a79607c03.png">

<img width="253" alt="image" src="https://user-images.githubusercontent.com/102153444/194557298-2e865686-39e0-43f7-9e58-940a0421cfce.png">

So the question or request for the feature: is there a possibility to group several layers as one that acts as an independent element on the map? So on clusterization grouped layers will be treated as one.

I'm pretty much satisfied with the abilities ShapeSource provides but I really need such behavior I've described above if it's not possible can you please provide me with some alternatives that may be used? I was thinking about MarketView but I'm not sure whether I will be able to implement clusterization.

**Comment by mfazekas** [comment]
Pls move this to discussions. Also I'm not sure I understand what you want to achieve. Not sure what layers are on your picture. Not sure if the issue is about blue starts not being in front, or it's about black and red icons overlapping or just overlap of red icons. Also clustering is a feature of symbol layer, are you referring to that?!  https://docs.mapbox.com/mapbox-gl-js/example/cluster/, or you mean something else?
