### ISSUE TITLE
[Bug][Android]: offlineManager.subscribe logs error Unable to set pack observer [TypeError: undefined is not a function]

### ISSUE THREAD

**Issue by ShepelE** [rnmapbox/maps#2865]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.13.0

### Platform

Android

### `@rnmapbox/maps` version

10.0.6

### Standalone component to reproduce

-

### Observed behavior and steps to reproduce

no native android implementation in node_modules/@rnmapbox/maps/android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.kt for method setPackObserver for call
`
await MapboxOfflineManager.setPackObserver(packName);
`
from node_modules/@rnmapbox/maps/src/modules/offline/offlineManager.ts from subscribe method

STR:
1. start loading offline map in android app
2. close the app
3. open app and call
`
MapboxGL.offlineManager.subscribe(packName, ...);
`

### Expected behavior

no error logged

**Comment by lowiebenoot** [comment]
I'm experiencing the same issue on 10.0.5

**Comment by mfazekas** [comment]
@ShepelE pls include a component, we can use to reproduce the issue, thanks!

**Comment by shancock884** [comment]
Hi,
I know this issue is closed... I am proving a component to reproduce as requested above.
Please let me know if it is preferred to re-open or I should transfer the pertinent information to a new issue?

I have also seen this console message, using rnmapbox 10.1.33, and Mapbox 11.8.0.

The following component can be used to show the error:
```javascript
import { Button } from "react-native";
import Mapbox from "@rnmapbox/maps";

export function OfflineMapsTest() {

    const testPressed = async () => {
        const nullfunc = () => {};
        
        // Start download
        await Mapbox.offlineManager.createPack({
            name: 'pack1',
            styleURL: Mapbox.StyleURL.SatelliteStreet,
            minZoom: 11,
            maxZoom: 16,
            bounds: [[0.005, 52.005], [0, 52]]
        }, nullfunc, nullfunc);

        // Register callbacks
        Mapbox.offlineManager.subscribe('pack1',
            (_p,s) => console.log("progress",s.percentage),
            (_p,e) => console.log("error",e.message)
        );
    }

    return <Button onPress={testPressed} title="Test"/>
}
```
The log messages shown are as follows.
```
 LOG  Unable to set pack observer [TypeError: MapboxOfflineManager.setPackObserver is not a function (it is undefined)]
 LOG  progress 0
 LOG  progress 25
 LOG  progress 50
 LOG  progress 75
 LOG  progress 100
```
This message seems to show because there is no 'setPackObserver' function in the Android Native module, so the try/catch will always trigger:
https://github.com/rnmapbox/maps/blob/b386d37a2169a66c9328e14ac553d8afab996082/src/modules/offline/offlineManager.ts#L369-L379
As the progress logs are showing as expected, I suspect the message is benign and this block of code could be removed.
