### ISSUE TITLE
`undefined method `pre_install' for nil:NilClass` when trying to setup for iOS.

### ISSUE THREAD

**Issue by Kikanye** [rnmapbox/maps#3172]
## Environment
- Dev OS: MacOS Sonoma 14.0

## Steps to reproduce

```sh   
react-native init sample --version react-native@0.60.5
cd sample
npm install --save @rnmapbox/maps
```
Follow the steps for iOS setup up until it says to run `pod install`.
After running pod install the error 

```
An error occurred while processing the pre-install hook of the Podfile.

undefined method `pre_install' for nil:NilClass
```
 shows up.

**Comment by mfazekas** [comment]
Sorry now I don't see any version there. But I'm not sure if you started with a new project or your existing project is not working. 

If you cannot reproduce with a  brand new project, please start a new project with the same rn version you have and compare package.json for different versions.

Please note that your issue is considered a [support request](https://github.com/rnmapbox/maps/wiki/Support) and we don't provide free [support](https://github.com/rnmapbox/maps/wiki/Support) thanks for the understanding.
