### ISSUE TITLE
Expo Prebuild Secret Key

### ISSUE THREAD

**Issue by thomas-coldwell** [rnmapbox/maps#3396]
Hi, I've just started setting up MapBox in my Expo app (following the linked guide here - https://rnmapbox.github.io/docs/install) and I apply the config plugin for it via an `app.config.ts` file as shown below so that I can store the `MAPBOX_SK` in a `.env` file that is not checked into source control. This works great, however, once `npx expo prebuild` is ran this then spits the SK out into the native `Podfile` and `gradle.properties` files which I want to keep checked into source control - the presence of the SK in these files now prevents me from keeping these in source control without leaking the secret key out.

```ts
import { ExpoConfig, ConfigContext } from "expo/config";

module.exports = ({ config }: ConfigContext): ExpoConfig => {
  return {
    name: config.name!,
    slug: config.slug!,
    ...config,
    plugins: [
      ...(config.plugins ?? []),
      [
        "@rnmapbox/maps",
        {
          RNMapboxMapsDownloadToken: process.env.MAPBOX_SK,
        },
      ],
    ],
  };
};
```

My question here is what is the correct approach using Expo to keep the secret key safe here? On the iOS and Android tabs in the installation guide it recommends placing the SK into the global gradle properties file or for iOS in a .netrc file (this is also recommended by the official mapbox guides e.g. https://docs.mapbox.com/ios/maps/guides/install/#configure-credentials).

Cheers! 🙌

**Comment by mfazekas** [comment]
@thomas-coldwell you can use .netrc and global grade properties for mapbox tokens. But those will not work if you use `eas` remote builds. I guess your's is a niche use case, where you want to use expo prebuild, you don't use eas and you want to check in the io/android to your CI and you don't want secrets there. 
Not sure what happens if you don't specifiy the download token in expo config.

Closing this as it's not something we plan to support, but we still accept pr for it.

**Comment by mfazekas** [comment]
@thomas-coldwell thanks much I'm not sure about the docs. My concern is keeping the docs simple, this is infomation 99% of users don't need,  so we can put it into an advanced guide, not sure.

**Comment by JordanHe** [comment]
@thomas-coldwell are you able to explain how you set up your project so that you can make a preview or production build with eas but making sure the mapbox secret key isn't exposed anywhere? not quite sure how to do it correctly.

**Comment by nixolas1** [comment]
@mfazekas I think this is less of a niche, as it seems the token is included in output bundles of normal (non-prebuild) EAS builds of our apps. So I think it affects all apps that use Expo with EAS builds.

Checked the Android apk version, and the secret key was included in the /assets/app.config file.
I don't feel like it's a big issue, as the scopes are for download only, but still not perfect.
Maybe a bit similar to Sentry's [issue](https://github.com/expo/sentry-expo/issues/321) with Auth token? They ended up reading directly from .env file instead of app.config I think.

We define it like this:
```
[
      "@rnmapbox/maps",
      {
        RNMapboxMapsImpl: "mapbox",
        RNMapboxMapsDownloadToken: process.env.MAPBOX_DOWNLOAD_TOKEN,
      },
    ],
```

**Comment by mfazekas** [comment]
@nixolas1 Thanks for the heads up. Yes we should probably clarify this in the  Doscs that this way the token is leaked via apk. And and implement and document a way to use eas/secrets envs. It will make expo config a bit more complicated, as eas secrets doesn't work on local builds.
